import "../styles/globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "MagicPortfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning >
        {children}
      </body>
    </html>
  );
}
